//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog2021N.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePages
    {
        public byte HomePageId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string TwitterLink { get; set; }
        public string InstagramLink { get; set; }
        public string GithubLink { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
